### ISSUE TITLE
그 외 모니터링 툴 설치 스크립트도 구할 수 있을까요?

### ISSUE THREAD

**Issue by carrotis** [sktelecom-oslab/taco-scripts#24]
안녕하세요 !!

Taco 스크립트 외에
Prometheus 및 EFK 에 대한 스크립트도 제공해주실 수 있을까요?
공개가 되지 않는 버전이라면  상관 없습니다!

감사합니다.

**Comment by bluejayA** [comment]
Prometheus나 EFK등은 설치를 위해 요구되는 하드웨어 사양이 좀 커지기도 하고, All-In-One와 같은 환경에서도 적어도 최소한의 사용은 가능한 정도로 Deploy 가능하게 만들 필요가 있어서요. 되는데로 공유드리도록 하겠습니다. 

스크립트는 다른건 없고 armada manifest (https://github.com/sktelecom-oslab/armada-manifests) 에 내용이 추가된다고 보시면 됩니다.

**Comment by bluejayA** [comment]
내부적으로 가능한데로 LMA쪽도 올리도록 하겠습니다.
