### ISSUE TITLE
Installing monitoring script 동작 안함 

### ISSUE THREAD

**Issue by bluejayA** [sktelecom-oslab/taco-scripts#7]
Instaling monitoring script (06-install-monitoring.sh) 실행 시 에러 발생

**Comment by ghost** [comment]
~/taco-kubespray의 path가 ~/apps/taco-kubespray로 변경되어야 합니다. 이 외에 다른 문제도 있을수도 있어요!

**Comment by bluejayA** [comment]
https://github.com/sktelecom-oslab/taco-scripts/commit/c05ef964bfebf40152d21f4b9b081161c4bdfd97
