### ISSUE TITLE
CentOS/Rhel 실행 시, root 계정 PATH 이슈

### ISSUE THREAD

**Issue by javarchoo** [sktelecom-oslab/taco-scripts#8]
CentOS/Rhel 에서는 "sudo -i" 로 root가 되면 $PATH에 /usr/local/bin이 안들어감.
"su - "로 root 가 되면  /usr/local/bin 이 $PATH에 들어가는데, 보통 운영환경에서는  root 패스워드를 일부러 설정하지 않는 경우도 있으므로 PATH=$PATH:/usr/local/bin 를 스크립트에 추가

**Comment by bluejayA** [comment]
PATH 설정은 12월에 반영되어 있습니다.

**Comment by javarchoo** [comment]
02번 스크립트에도 반영합니다.
